--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/TestCustomUI
build-by-default: true
branches:
- main
projects:
  TestCustomUI:
    path: ""
    libs:
    - src: Terpz710/customui/customui
      version: "^3.0.0"
...
